generate_topic_task:
  description: >
    bring up a current sports topic. The topic should be recent sporting event or news story within the last 30 days.
  expected_output: >
    The topic should be recent sporting event or news story within the last 30 days. It should only be a topic, don't introduce what about the topic should be debated on.
  agent: moderator

generate_hot_take_task:
  description: >
    Generate a hot take based on the given {topic}.
  expected_output: >
    The hot take should be appropriate for general audiences. Only return the hot take, no other text. The hot take should be appropriate for general audiences.
  agent: junior_debator

improve_hot_take_task:
  description: >
    Improve upon the given {hot_take} by providing a more detailed and convincing argument. Provide facts and examples to support your points.
  expected_output: >
    Only return the improved hot take, no other text. The hot take should be appropriate for general audiences.
  agent: senior_debator

counter_hot_take_task:
  description: >
    Argue against the given {improved_hot_take} by providing a counter argument. Provide facts and examples to support your points.
  expected_output: >
    Only return the counter argument, no other text. The counter argument should be appropriate for general audiences.
  agent: counter_debator
